api = "0.10"

[buildpack]
id = "paketo-buildpacks/apt"
version = "0.3.0"
name = "Paketo Buildpack for Apt"
homepage = "https://github.com/paketo-buildpacks/apt"
description = "A Cloud Native Buildpack that that allows you to install additional dependencies for both build and runtime using Apt"
keywords = ["apt", "packages", "ubuntu", "debian"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
